Stepanov\MarketBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    image:
      type: string
      length: 255
      nullable: true
    price:
      type: float
    created_at:
      type: string
  manyToMany:
    categories:
      targetEntity: Category
      inversedBy: product
      joinTable:
        name: product_categories
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id

